Irangallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('blog/', include('post.urls'), name='blog'),
    path('category/', include('category.urls'), name='category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
import profile

from django.contrib.auth import logout
from django.urls import path
from .views import login_site, signup_site, logout_site, writer, profile

app_name = 'accounts'
urlpatterns = [
    path('login/', login_site, name='login'),
    path('logout/', logout_site, name='logout'),
    path('signup/', signup_site, name='signup'),
    path('writer/<str:user_name>', writer, name='writer'),
    path('user/<int:pk>', profile, name='profile'),
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'
urlpatterns = [
    path('', home, name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, number, password, **extra_fields):
        number = number
        if not number or len(number) != 11 or not number.startswith('09'):
            raise ValueError('Please enter a right number')

        user = self.create(number=number, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, number, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(number, password, **extra_fields)


class User(AbstractUser):
    bio      = models.TextField(max_length=500, blank=True, null=True)
    picture  = models.ImageField(upload_to='account/user_pictures', default='account/user_pictures/default.jpg')
    number   = models.CharField(max_length=11, unique=True)
    username = models.CharField(max_length=20, unique=True)

    USERNAME_FIELD  = 'number'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return f'{self.username}-{self.number}'


class LinkUser(models.Model):
    user      = models.ForeignKey(User, on_delete=models.CASCADE, related_name='links_user')
    telegram  = models.URLField(max_length=100, blank=True, null=True)
    x         = models.URLField(max_length=100, blank=True, null=True)
    instagram = models.URLField(max_length=100, blank=True, null=True)
    github    = models.URLField(max_length=100, blank=True, null=True)
    facebook  = models.URLField(max_length=100, blank=True, null=True)
    youtube   = models.URLField(max_length=100, blank=True, null=True)
    linkedin  = models.URLField(max_length=100, blank=True, null=True)

post/models.py
from django.db import models

import post
from accounts.models import User
from category.models import Category
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title       = models.CharField(max_length=150)
    category    = models.ManyToManyField(Category, related_name='posts', blank=True)
    body        = models.TextField()
    created     = models.DateTimeField(auto_now_add=True)
    writer      = models.ForeignKey(User, on_delete=models.CASCADE)
    views       = models.ManyToManyField(User, related_name='users_views', blank=True)
    image       = models.ImageField(upload_to='post/images/')
    slider      = models.BooleanField(default=False)

    def linkpost(self):
        return reverse('post:post_page', kwargs={'pk':self.id})

    def has_seen(self, user):
        return self.views.filter(id=user.id).exists()

    def __str__(self):
        return f"{self.title[:30]}...-{self.created}"

class Comment(models.Model):
    post    = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body    = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    user    = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')


    def __str__(self):
        return f"{self.body[:30]}..."

accounts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.models import User
from post.models import Post


# Create your views here.
def login_site(request):
    if request.user.is_authenticated:
        return redirect('home:home')

    if not request.method == "POST":
        return render(request, 'accounts/login.html')

    number   = request.POST.get("number")
    password = request.POST.get("password")

    user     = authenticate(request, number=number, password=password)

    if user is not None:
        login(request, user)
        return redirect('home:home')
    else:
        return render(request, "accounts/login.html", {'message': 'Invalid number or password.'})

def logout_site(request):
    logout(request)
    return redirect('home:home')

def signup_site(request):
    if request.user.is_authenticated:
        return redirect('home:home')

    if not request.method == "POST":
        return render(request, "accounts/signup.html")

    number     = request.POST.get("number")
    username   = request.POST.get("username")
    first_name = request.POST.get("first_name")
    last_name  = request.POST.get("last_name")
    password   = request.POST.get("password")

    messages   = dict()

    if User.objects.filter(number=number).exists() or User.objects.filter(username=username).exists():
        if User.objects.filter(number=number).exists():
            messages['number_message'] = 'Number already exists.'

        if User.objects.filter(username=username).exists():
            messages['username_message'] = 'Username already exists.'

        return render(request, "accounts/signup.html", {'messages': messages})


    user = User.objects.create_user(number=number, password=password, first_name=first_name, last_name=last_name, username=username)

    login(request, user)

    return redirect('home:home')

def writer(request, user_name):
    user       = User.objects.get(username=user_name)
    posts_list = Post.objects.filter(writer=user)
    paginator  = Paginator(posts_list, 10)
    page       = request.GET.get('q')
    posts      = paginator.get_page(page)

    return render(request, 'accounts/author.html', {'posts': posts, 'user': user})

def profile(request, pk):
    if not request.user.is_authenticated and not request.user.id == pk:
        return redirect('home:home')

    user = User.objects.get(id=pk)
    if not request.method == "POST":
        return render(request, 'accounts/profile.html', {'user': user})

    messages = dict()
    if request.POST.get("username") != user.username and User.objects.filter(username=request.POST.get("username")).exists():
        messages['username_message'] =  'username already in use.'
    else:
        user.username = request.POST.get("username")

    if request.POST.get("email") != user.email and User.objects.filter(email=request.POST.get("email")).exists():
        messages['email_message'] = 'email already in use.'
    else:
        user.email = request.POST.get("email")

    if request.POST.get("number") != user.number and User.objects.filter(number=request.POST.get("number")).exists():
        messages['number_message'] = 'number already in use.'
    else:
        user.number = request.POST.get("number")

    user.first_name = request.POST.get("first_name")
    user.last_name  = request.POST.get("last_name")
    user.bio        = request.POST.get("bio")
    if request.FILES.get("picture"):
        user.picture = request.FILES.get("picture")
    user.save()

    if messages:
        return render(request, 'accounts/profile.html', {'user': user, 'messages': messages})


    return render(request, 'accounts/profile.html', {'user': user})

accounts/templates/accounts/author.html
<!doctype html>
{% extends 'base.html' %}

{% block title %}{{ user.username }}{% endblock %}
{% block content %}



<main class="main">
        <!--author-->
        <section class="banner">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6 col-md-8 col-sm-11 m-auto">
                        <div class="banner__author ">
                            <div class="banner__author-image">
                                <a href="{% url 'accounts:writer' user_name=user.username %}" class="image">
                                    <img src="{{ user.picture.url }}" alt="" class="banner__author-img">
                                </a>
                            </div>
                            <div class="banner__author-content">
                                <h5 class="banner__author-name"> Hi, I'm {{ user.first_name }} {{ user.last_name }}</h5>
                                <div class="btn-link">{{ user.post_set.count }} posts</div>
                                <p class="banner__author-bio">
                                    {% if user.bio %}
                                        {{ user.bio }}
                                    {% endif %}
                                </p>
                            {% if user.links_user.all %}
                                <ul class="list-inline social-media social-media--layout-two">
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.facebook %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.facebook }}" class="social-media__link color-facebook" ><i class="bi bi-facebook"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.telegram %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.telegram }}" class="social-media__link color-twitter" ><i class="bi bi-telegram"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.x %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.x }}" class="social-media__link color-x" ><i class="bi bi-x"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.instagram %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.instagram }}" class="social-media__link color-instagram" ><i class="bi bi-instagram"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.github %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.github }}" class="social-media__link color-black" ><i class="bi bi-github"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.youtube %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.youtube }}" class="social-media__link color-youtube" ><i class="bi bi-youtube"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                {% for link_user in user.links_user.all %}
                                    {% if link_user.linkedin %}
                                    <li class="social-media__item">
                                        <a href="{{ link_user.linkedin }}" class="social-media__link color-twitter" ><i class="bi bi-linkedin"></i></a>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                </ul>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <!--grid-layout-->
        <section class="mt-90">
            <div class="container-fluid">
                <div class="row">
                    {% for post in posts %}
                    <!--Post-->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="post-card post-card--default">
                            <div class="post-card__image">
                                <a href="{{ post.linkpost }}" >
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}" height="900" width="1200">
                                </a>
                            </div>
                            
                            <div class="post-card__content">
                                {% for c in post.category.all %}
                                    <a href="{{ c.linkcat }}" class="category">{{ c.title }}</a>
                                {% endfor %}
                                <h5 class="post-card__title">
                                    <a href="{{ post.linkpost }}" class="post-card__title-link">{{ post.title }}</a>
                                </h5>
                                <p class="post-card__exerpt">{{ post.body|truncatechars:120 }}
                                </p>
                                
                                <ul class="post-card__meta list-inline">
                                    <li class="post-card__meta-item">
                                        <a href="{% url 'accounts:writer' user_name=post.writer.username %}" class="post-card__meta-link">
                                            <img src="{{ post.writer.picture.url }}" alt="" class="post-card__meta-img">
                                        </a>
                                    </li>
                                    <li class="post-card__meta-item ">
                                        <a href="{% url 'accounts:writer' user_name=post.writer.username %}" class="post-card__meta-link">{{ post.writer.first_name }} {{ post.writer.last_name }}</a>
                                    </li>
                                    <li class="post-card__meta-item"> 
                                        <span class="dot"></span> {{ post.created }}
                                    </li>
                                    <li class="post-card__meta-item"> <span class="dot"></span>{{ post.views.count }} View</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if posts %}
                <!--pagination-->
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="pagination list-inline">
                            {% if posts.has_previous %}
                                <li class="pagination__item"><a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="pagination__link"><i class="bi bi-arrow-left pagination__icon"></i></a></li>
                            {% endif %}

                            {% for page in posts.paginator.page_range %}
                                {% if page >= posts.number|add:'-2' and page <= posts.number|add:'2' %}
                                    <li class="pagination__item{% if page == posts.number %} pagination__item--active{% endif %}">
                                        <a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="pagination__link">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if posts.has_next %}
                                <li class="pagination__item"><a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="pagination__link"><i class="bi bi-arrow-right pagination__icon"></i></a></li>
                            {% endif %}
                        </ul> 
                    </div>
                </div>
                {% endif %}
            </div>
        </section>
    </main>

{% endblock %}

accounts/templates/accounts/login.html
<!doctype html>
{% extends 'base.html' %}

{% block title %}login page{% endblock %}

{% block content %}
    <main class="main">
        <!--Login-->
        <section class="m-top mb-60">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 m-auto">
                    <div class="widget">
                        <h5 class="widget__title">Login</h5>
                        <form  action="" class="widget__form" method="post">
                            {% csrf_token %}
                            {% if message  %}
                                <h6 class="text-danger"> {{ message }}</h6><br>
                            {% endif %}
                            <div class="form-group">
                                <input type="text" class="form-control widget__form-input" placeholder="phone number..." name="number" required="required" maxlength="11">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control widget__form-input" placeholder="Password*" name="password" required="required">
                            </div>
                            <div class="widget__form-btn">
                                <button type="submit" class="btn-custom">Login Now</button>
                            </div>
                            <p class="widget__form-text">Don't have an account?<a href="{% url 'accounts:signup' %}" class="widget__form-link">Create One</a>
                            </p>
                        </form>
                    </div>
                    </div>

                </div>
                    
            </div>
        </section>
    </main>
{% endblock %}

accounts/templates/accounts/profile.html
<!doctype html>
{% extends 'base.html' %}


{% block title %}Profile page{% endblock %}


{% block content %}


<main class="main">
        <!--contact us-->
        <section class="m-top">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 m-auto">
                        <div class="contact">
                            {% if user.picture != "account/user_pictures/default.jpg" %}
                            <div class="google-map contact__google-map">
                                <img src="{{ user.picture.url }}" class="profile__picture" height="900" width="900" alt="{{ user.username }}">
                            </div>
                            {% endif %}
                            <form action="{% url 'accounts:profile' user.id %}" method="POST" enctype="multipart/form-data" class="widget__form contact__form" id="main_contact_form">
                                {% csrf_token %}
                                <h3 class="widget__form-title">Your account information</h3>
                                <div class="alert alert-success contact__msg" style="display: none" role="alert">
                                    Your change was sent successfully.
                                </div>
                                <h6 class="text-danger">{{ messages.number_message }}</h6>
                                 <div class="form-group">
                                    <input type="text" name="number" id="number" class="form-control widget__form-input" placeholder="You number..." required="required" value="{{ user.number }}" >
                                </div>
                                <h6 class="text-danger">{{ messages.username_message }}{{ username_message }}</h6>
                                 <div class="form-group">
                                    <input type="text" name="username" id="username" class="form-control widget__form-input" placeholder="Your Username..." value="{{ user.username }}" required="required">
                                </div>
                                <h6 class="text-danger">{{ messages.email_message }}</h6>
                                <div class="form-group">
                                    <input type="email" name="email" id="email" class="form-control widget__form-input" placeholder="Your email..." value="{{ user.email }}" >
                                </div>
                                 <div class="form-group">
                                    <input type="text" name="first_name" id="first_name" class="form-control widget__form-input" placeholder="Your First name..." required="required" value="{{ user.first_name }}" >
                                </div>
                                <div class="form-group">
                                    <input type="text" name="last_name" id="last_name" class="form-control widget__form-input" placeholder="Your Last name..." required="required" value="{{ user.last_name }}" >
                                </div>
                                <div class="form-group">
                                    <textarea name="bio" id="bio" cols="30" rows="5" class="form-control widget__form-input" placeholder="Your bio..." >{{ user.bio }}</textarea>
                                </div>
                                <h5>profile picture</h5><br>
                                <div class="form-group">
                                    <input type="file" name="picture" id="picture" class="form-control widget__form-input">
                                </div>
                                <button type="submit" name="submit" class="btn-custom">Change</button>
                            </form>
                        </div> 
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

accounts/templates/accounts/signup.html
<!doctype html>
{% extends 'base.html' %}

{% block title %}signup page{% endblock %}

{% block content %}

    <main class="main">
        <!--register-->
        <section class="m-top  mb-60">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6 m-auto">
                        <div class="widget">
                            <h5 class="widget__title">Sign up</h5>
                            <form  class="widget__form contact_form " method="post">
                                {% csrf_token %}
                                <h6 class="text-danger"> {{ messages.number_message }}</h6>
                                <div class="form-group">
                                    <input type="text" class="form-control widget__form-input" placeholder="your phone number..." name="number" required="required" maxlength="11">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control widget__form-input" placeholder="Enter password..." name="password" required="required">
                                </div>
                                <h6 class="text-danger"> {{ messages.username_message }}</h6>
                                <div class="form-group">
                                    <input type="text" class="form-control widget__form-input" placeholder="Enter username..." name="username" required="required" maxlength="20">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control widget__form-input" placeholder="Enter your First name..." name="first_name" required="required" maxlength="20">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control widget__form-input" placeholder="Enter your Last name..." name="last_name" required="required" maxlength="20">
                                </div>
                                <div class="widget__form-btn">
                                    <button type="submit" class="btn-custom">Sign Up Now</button>
                                </div>
                                <p class="widget__form-text">Already have an account? 
                                    <a href="{% url 'accounts:login' %}" class="widget__form-link">Login</a>
                                </p>
                            </form>
                        </div> 
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}